# Generated by Django 4.0.3 on 2023-01-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wilaya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('Wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilaya', to='wilaya.wilaya')),
            ],
        ),
    ]
